### PR TITLE
Loosen jinja versions requirements - fixes #41

### LINKED ISSUE #41: Jinja2 dependency increased to include Jinja2 3.x.x
```
installrequires = ['PyYAML', 'Jinja2>1,<4',]
```
All tests pass. Updating the dependency allows HiYaPico to work with the latest release of Flask and Jinja.

### PR DESCRIPTION
**Pull request by AvnerCohen**

### CODE REVIEW

**Review by look4regev — APPROVED** [review]

**Comment by AvnerCohen** [comment]
@zerwes Any chance this can be merged ? this is blocking us from using the lib and I would like to avoid forking just for this simple change.

**Comment by zerwes** [comment]
thank you for the fix

**Comment by AvnerCohen** [comment]
Thanks @zerwes  !! Can this please be pushed to pypi ?

**Comment by AvnerCohen** [comment]
Thanks @zerwes Totally understand life and so.

If this is the case, I would actually suggest to drop python 2.7 support and publish this PR both together as part of 0.5

This way there will be no need to spend any time on solving this for a minor patch on 0.4x.

**Comment by look4regev** [comment]
@zerwes ping please :)
Can we follow @AvnerCohen 's suggestion so we can have a new version in pypi?

**Pull request merged**
