### PR TITLE
Further fine-tuning of Debian packaging

### PR DESCRIPTION
**Pull request by smoe**
Many thanks for your prior positive reaction to what I did to debian/*. Ping me if you would like to maintain the package in Debian yourself. To avoid going through PRs and to grant more folks the opportunity to further improve on the packaging, I would like to bring the package under team management on https://salsa.debian.org/python-team.

Next step in the development of the packaging would be the integration of your testing routines with what salsa offers - later :)

### CODE REVIEW

**Comment by zerwes** [comment]
> Ping me if you would like to maintain the package in Debian yourself.

I do not think that the role of the developer and the maintainer should be in one.
I will take care of HiYaPyCo here, and you or someone can take care of the debian specific packaging stuff ...

**Review by zerwes — CHANGES_REQUESTED** [review]
I think this PR includes some changes that should only be done in the debian context:
 * `debian/changelog` : debian releases should not be included here
 * `debian/control`: **Uploaders** should only be set in the debian context

All other changes are OK for me

**Comment by zerwes** [comment]
> I would like to bring the package under team management on https://salsa.debian.org/python-team.

OK for me. Do you need something from me for this?
Sorry, my last debian maintainier experience was not to deep and in addition 12 years ago ...

**Comment by smoe** [comment]
All fine, I think. I'll drop you a ping when the package arrived.

**Comment by zerwes** [comment]
Thanks for the update.
If I can support the packaging process in any way, just drop me a note.
In order to coordinate the communication on this topic, you can create a issue here for this purpose, if you like.
Greetings

**Pull request merged**
